server:
    port: 6789
    context-path: /

logging:
    level:
        com.tramy.sync: DEBUG
    file: kafka.log

spring:
    datasource:
        url: jdbc:sqlserver://192.168.0.110:1433;DatabaseName=tramy
        username: sa
        password: 12345678
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
        name: firehome
        #url: jdbc:mysql://localhost:3306/test
        #username: root
        #password:
        # 使用druid数据源
        #type: com.alibaba.druid.pool.DruidDataSource
        #driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request

#以下属性不可用
#mybatis:
#    pagehelper:
#        dialect: mysql
#        reasonable: true
#        supportMethodsArguments: true
#        returnPageInfo: check
#        params: count=countSql
#    mapper:
#        mappers: MyMapper
#        notEmpty: true
#        style: camelhump
#    sqlSessionFactoryBean:
#        mapperLocations:
#            - classpath:mapper/*.xml
#            - classpath:mapper2/*.xml
#        typeAliasesPackage: tk.mybatis.springboot.model
#    mapperScanner:
#        basePackage: tk.mybatis.springboot.mapper
kafka:
  broker:
    address: 192.168.0.231:9092
  zookeeper:
    connect: 192.168.0.231:2181
  topic: tramy.topic
  messageKey: tramy.key