package com.tramy.sync.mapper;

import com.tramy.sync.model.Customer;
import com.tramy.sync.model.CustomerExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CustomerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    int countByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    int deleteByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    int insert(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    int insertSelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    List<Customer> selectByExample(CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    Customer selectByPrimaryKey(BigDecimal customerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Customer record, @Param("example") CustomerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Customer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table TF_SSS_CUSTOMER
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Customer record);
}